version: "3.8"
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cost_accounting
      - POSTGRES_PASSWORD=cost_accounting
      - POSTGRES_DB=cost_accounting_dev

volumes:
  postgres_data: