version: "3.8"
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cost_accounting
      - POSTGRES_PASSWORD=cost_accounting
      - POSTGRES_DB=cost_accounting_dev

  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A cost_accounting.celery worker --pool=solo --loglevel=info
    volumes:
      - ./cost_accounting:/cost_accounting
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web
  celery-beat:
    build: .
    command: celery -A cost_accounting beat --loglevel=info
    volumes:
      - ./cost_accounting:/cost_accounting
    env_file:
      - ./.env
    depends_on:
      - celery

volumes:
  postgres_data: